# Generated by Django 5.2.16 on 2026-07-26 06:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_storehome_storehomeusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='storehome',
            name='managers',
            field=models.ManyToManyField(help_text='Users who are permitted to manage inventory', to=settings.AUTH_USER_MODEL, verbose_name='Managers'),
        ),
        migrations.DeleteModel(
            name='StorehomeUsers',
        ),
    ]
