# Generated by Django 5.2.16 on 2026-07-26 06:31

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_storehome_managers_delete_storehomeusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kibble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=16, verbose_name='Barcode')),
                ('brand', models.CharField(max_length=100, verbose_name='Brand/Company')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Photo')),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Estimated Price')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('disallowed', models.BooleanField(default=False, verbose_name='Disallowed')),
                ('in_production', models.BooleanField(default=True, verbose_name='In Production')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('life_stages', models.CharField(choices=[('UNK', 'Unknown'), ('PUP', 'Puppy'), ('ADL', 'Adult'), ('ALL', 'All-Stages'), ('SNR', 'Senior')], default='UNK', max_length=3)),
                ('proteins', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CHKN', 'Chicken'), ('BEEF', 'Beef'), ('LAMB', 'Lamb'), ('TURK', 'Turkey'), ('DUCK', 'Duck'), ('SALM', 'Salmon'), ('FISH', 'Fish (Unspecified)'), ('WTFS', 'Whitefish'), ('PORK', 'Pork'), ('VENI', 'Venison'), ('BSON', 'Bison'), ('RBBT', 'Rabbit')], max_length=59, verbose_name='Proteins')),
                ('weight', models.FloatField(verbose_name='Weight')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
