# Generated by Django 5.2.16 on 2026-07-26 06:42

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_kibble'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('barcode', models.CharField(max_length=16, verbose_name='Barcode')),
                ('brand', models.CharField(max_length=100, verbose_name='Brand/Company')),
                ('country_of_origin', models.CharField(blank=True, max_length=100, verbose_name='Country of Origin')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Photo')),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Estimated Price')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('disallowed', models.BooleanField(default=False, verbose_name='Disallowed')),
                ('in_production', models.BooleanField(default=True, verbose_name='In Production')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('life_stages', models.CharField(choices=[('UNK', 'Unknown'), ('PUP', 'Puppy'), ('ADL', 'Adult'), ('ALL', 'All-Stages'), ('SNR', 'Senior')], default='UNK', max_length=3)),
                ('proteins', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CHKN', 'Chicken'), ('BEEF', 'Beef'), ('LAMB', 'Lamb'), ('TURK', 'Turkey'), ('DUCK', 'Duck'), ('SALM', 'Salmon'), ('FISH', 'Fish (Unspecified)'), ('WTFS', 'Whitefish'), ('PORK', 'Pork'), ('VENI', 'Venison'), ('BSON', 'Bison'), ('RBBT', 'Rabbit')], max_length=59, verbose_name='Proteins')),
                ('grain_free', models.BooleanField(default=False, verbose_name='Grain-Free')),
                ('limited_ingrediant', models.BooleanField(default=False, verbose_name='Limited Ingredient')),
                ('special_diet', models.CharField(choices=[('NONE', 'None'), ('SENS', 'Sensitive Stomach'), ('WGHT', 'Weight Management'), ('DENT', 'Dental Health'), ('DIGE', 'Digestive Health'), ('JONT', 'Joint Health'), ('SKIN', 'Skin & Coat')], default='NONE', max_length=4, verbose_name='Special Diet')),
                ('can_size', models.FloatField(verbose_name='Can Size')),
                ('texture', models.CharField(blank=True, choices=[('PATE', 'Paté'), ('CHGR', 'Chunks in Gravy'), ('STEW', 'Stew'), ('SHRD', 'Shreds')], max_length=4, verbose_name='Texture')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='kibble',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=100, verbose_name='Country of Origin'),
        ),
        migrations.AddField(
            model_name='kibble',
            name='grain_free',
            field=models.BooleanField(default=False, verbose_name='Grain-Free'),
        ),
        migrations.AddField(
            model_name='kibble',
            name='kibble_size',
            field=models.CharField(blank=True, choices=[('SM', 'Small'), ('MD', 'Medium'), ('LG', 'Large')], max_length=2, verbose_name='Kibble Size'),
        ),
        migrations.AddField(
            model_name='kibble',
            name='limited_ingrediant',
            field=models.BooleanField(default=False, verbose_name='Limited Ingredient'),
        ),
        migrations.AddField(
            model_name='kibble',
            name='name',
            field=models.CharField(default='Food', max_length=200, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kibble',
            name='special_diet',
            field=models.CharField(choices=[('NONE', 'None'), ('SENS', 'Sensitive Stomach'), ('WGHT', 'Weight Management'), ('DENT', 'Dental Health'), ('DIGE', 'Digestive Health'), ('JONT', 'Joint Health'), ('SKIN', 'Skin & Coat')], default='NONE', max_length=4, verbose_name='Special Diet'),
        ),
    ]
