# Generated by Django 5.2.16 on 2026-07-29 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0005_canned_kibble_country_of_origin_kibble_grain_free_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='Product ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('date_stored', models.DateField(auto_now_add=True, verbose_name='Date Stored')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Product Type')),
                ('storehome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_items', to='core.storehome', verbose_name='Storehome')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_storag_content_09b6d2_idx')],
            },
        ),
    ]
