# Generated by Django 5.2.16 on 2026-07-29 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_userprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storehome',
            name='managers',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='managed_storehome',
            field=models.ForeignKey(blank=True, help_text='The storehome this user is permitted to manage inventory for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers', to='core.storehome', verbose_name='Managed Storehome'),
        ),
    ]
