# Generated by Django 5.2.16 on 2026-07-29 03:52

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0008_remove_storehome_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('username'), name='userprofile_username_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='userprofile_email_ci_unique'),
        ),
    ]
