# Generated by Django 5.2.16 on 2026-07-30 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Canned',
        ),
        migrations.DeleteModel(
            name='Kibble',
        ),
        migrations.DeleteModel(
            name='StorageItem',
        ),
    ]
