# Generated by Django 5.2.16 on 2026-07-30 03:05

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0010_delete_canned_delete_kibble_delete_storageitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('barcode', models.CharField(max_length=16, verbose_name='Barcode')),
                ('brand', models.CharField(max_length=100, verbose_name='Brand/Company')),
                ('country_of_origin', models.CharField(blank=True, max_length=100, verbose_name='Country of Origin')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Photo')),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Estimated Price')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('disallowed', models.BooleanField(default=False, verbose_name='Disallowed')),
                ('in_production', models.BooleanField(default=True, verbose_name='In Production')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.product')),
                ('life_stages', models.CharField(choices=[('UNK', 'Unknown'), ('PUP', 'Puppy'), ('ADL', 'Adult'), ('ALL', 'All-Stages'), ('SNR', 'Senior')], default='UNK', max_length=3)),
                ('proteins', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CHKN', 'Chicken'), ('BEEF', 'Beef'), ('LAMB', 'Lamb'), ('TURK', 'Turkey'), ('DUCK', 'Duck'), ('SALM', 'Salmon'), ('FISH', 'Fish (Unspecified)'), ('WTFS', 'Whitefish'), ('PORK', 'Pork'), ('VENI', 'Venison'), ('BSON', 'Bison'), ('RBBT', 'Rabbit')], max_length=59, verbose_name='Proteins')),
                ('grain_free', models.BooleanField(default=False, verbose_name='Grain-Free')),
                ('limited_ingrediant', models.BooleanField(default=False, verbose_name='Limited Ingredient')),
                ('special_diet', models.CharField(choices=[('NONE', 'None'), ('SENS', 'Sensitive Stomach'), ('WGHT', 'Weight Management'), ('DENT', 'Dental Health'), ('DIGE', 'Digestive Health'), ('JONT', 'Joint Health'), ('SKIN', 'Skin & Coat')], default='NONE', max_length=4, verbose_name='Special Diet')),
            ],
            bases=('core.product',),
        ),
        migrations.CreateModel(
            name='Canned',
            fields=[
                ('food_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.food')),
                ('can_size', models.FloatField(verbose_name='Can Size')),
                ('texture', models.CharField(blank=True, choices=[('PATE', 'Paté'), ('CHGR', 'Chunks in Gravy'), ('STEW', 'Stew'), ('SHRD', 'Shreds')], max_length=4, verbose_name='Texture')),
            ],
            bases=('core.food',),
        ),
        migrations.CreateModel(
            name='Kibble',
            fields=[
                ('food_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.food')),
                ('weight', models.FloatField(verbose_name='Weight')),
                ('kibble_size', models.CharField(blank=True, choices=[('SM', 'Small'), ('MD', 'Medium'), ('LG', 'Large')], max_length=2, verbose_name='Kibble Size')),
            ],
            bases=('core.food',),
        ),
        migrations.CreateModel(
            name='StorageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='Product ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('date_stored', models.DateField(auto_now_add=True, verbose_name='Date Stored')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Product Type')),
                ('storehome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_items', to='core.storehome', verbose_name='Storehome')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_storag_content_09b6d2_idx')],
            },
        ),
    ]
