# Generated by Django 5.2.16 on 2026-07-31 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_product_food_canned_kibble_storageitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='grain_free',
        ),
        migrations.RemoveField(
            model_name='food',
            name='limited_ingrediant',
        ),
        migrations.RemoveField(
            model_name='food',
            name='special_diet',
        ),
    ]
