# Generated by Django 5.2.16 on 2026-07-31 03:06

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_food_grain_free_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='special_diet',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('NONE', 'None'), ('SENS', 'Sensitive Stomach'), ('WGHT', 'Weight Management'), ('DENT', 'Dental Health'), ('DIGE', 'Digestive Health'), ('JONT', 'Joint Health'), ('SKIN', 'Skin & Coat'), ('LIMI', 'Limited Ingredient'), ('GRAI', 'Grain-Free')], max_length=44, verbose_name='Special Diet'),
        ),
    ]
