# Generated by Django 5.2.16 on 2026-07-31 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_food_special_diet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='life_stages',
            field=models.CharField(choices=[('UNK', 'Unknown'), ('PUP', 'Puppy'), ('ADL', 'Adult'), ('ALL', 'All-Stages'), ('SNR', 'Senior')], default='UNK', max_length=3, verbose_name='Life Stage'),
        ),
    ]
