# Generated by Django 5.2.16 on 2026-07-31 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_food_life_stages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(max_length=16, unique=True, verbose_name='Barcode'),
        ),
    ]
