# Generated by Django 5.2.16 on 2026-07-31 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_product_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storehome',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='storehome',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
