# Generated by Django 5.2.16 on 2026-07-31 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_storehome_address_alter_storehome_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canned',
            name='can_size',
        ),
        migrations.AlterField(
            model_name='kibble',
            name='weight',
            field=models.FloatField(verbose_name='Bag Weight (lbs)'),
        ),
    ]
