# Generated by Django 5.2.16 on 2026-07-31 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_canned_can_size_alter_kibble_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kibble',
            name='weight',
            field=models.FloatField(verbose_name='Bag Weight'),
        ),
    ]
