# Generated by Django 5.2.16 on 2026-07-31 05:10

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_kibble_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='special_diet',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SENS', 'Sensitive Stomach'), ('WGHT', 'Weight Management'), ('DENT', 'Dental Health'), ('DIGE', 'Digestive Health'), ('JONT', 'Joint Health'), ('SKIN', 'Skin & Coat'), ('LIMI', 'Limited Ingredient'), ('GRAI', 'Grain-Free')], max_length=39, verbose_name='Special Diet'),
        ),
    ]
