# Generated by Django 5.2.16 on 2026-08-02 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_food_special_diet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kibble',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Bag Weight'),
        ),
    ]
