# Generated by Django 5.2.16 on 2026-08-02 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_kibble_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='updater_class',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Updater Class'),
        ),
        migrations.AddField(
            model_name='product',
            name='updater_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Updater Data'),
        ),
        migrations.AddField(
            model_name='product',
            name='updater_last_updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updater Last Updated'),
        ),
    ]
