# Generated by Django 5.2.16 on 2026-08-02 06:08

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_product_updater_class_product_updater_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='proteins',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CHKN', 'Chicken'), ('BEEF', 'Beef'), ('LAMB', 'Lamb'), ('TURK', 'Turkey'), ('DUCK', 'Duck'), ('SALM', 'Salmon'), ('FISH', 'Fish (Unspecified)'), ('WTFS', 'Whitefish'), ('PORK', 'Pork'), ('VENI', 'Venison'), ('BSON', 'Bison'), ('RBBT', 'Rabbit'), ('OTHR', 'Other')], max_length=64, verbose_name='Proteins'),
        ),
    ]
