# Generated by Django 5.2.16 on 2026-08-02 06:19

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_food_protein_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='missing_data',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('NAME', 'Missing Product Name'), ('BRAND', 'Missing Brand Info'), ('DISA', 'Disallowed'), ('PROT', 'Missing Protein Info'), ('WGHT', 'Missing Bag Weight')], max_length=32, verbose_name='Missing Data'),
        ),
        migrations.AlterField(
            model_name='food',
            name='proteins',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CHKN', 'Chicken'), ('BEEF', 'Beef'), ('BSON', 'Bison'), ('DUCK', 'Duck'), ('FISH', 'Fish (Unspecified)'), ('LAMB', 'Lamb'), ('PORK', 'Pork'), ('RBBT', 'Rabbit'), ('SALM', 'Salmon'), ('TURK', 'Turkey'), ('VENI', 'Venison'), ('WTFS', 'Whitefish'), ('OTHR', 'Other')], max_length=64, verbose_name='Proteins'),
        ),
    ]
