# Generated by Django 5.2.16 on 2026-08-02 06:23

from django.db import migrations, models


def refresh_data_warnings(apps, schema_editor):
    from core.models import Product

    for product in Product.objects.select_related(*Product.TYPE_SELECT_RELATED).iterator():
        product.specific.save(update_fields=["data_warnings"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_product_missing_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='missing_data',
        ),
        migrations.AddField(
            model_name='product',
            name='data_warnings',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Data Warnings'),
        ),
        migrations.RunPython(refresh_data_warnings, migrations.RunPython.noop),
    ]
