# Generated by Django 5.2.16 on 2026-08-05 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0029_storageitem_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageItemIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intake_date', models.DateTimeField(auto_now_add=True, verbose_name='Intake Date')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Count')),
                ('product_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Product Class')),
                ('storehome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_item_intakes', to='core.storehome', verbose_name='Storehome')),
            ],
        ),
        migrations.CreateModel(
            name='StorageItemOuttake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outtake_date', models.DateTimeField(auto_now_add=True, verbose_name='Outtake Date')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Count')),
                ('product_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Product Class')),
                ('storehome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_item_outtakes', to='core.storehome', verbose_name='Storehome')),
            ],
        ),
    ]
