# Generated by Django 5.2.16 on 2026-08-07 19:23

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_storageitemmovement_drop_product_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='proteins',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CHKN', 'Chicken'), ('BEEF', 'Beef'), ('BSON', 'Bison'), ('DUCK', 'Duck'), ('FISH', 'Fish (Unspecified)'), ('HAKE', 'Hake'), ('KANG', 'Kangaroo'), ('LAMB', 'Lamb'), ('PORK', 'Pork'), ('RBBT', 'Rabbit'), ('SALM', 'Salmon'), ('TROT', 'Trout'), ('TURK', 'Turkey'), ('VENI', 'Venison'), ('WTFS', 'Whitefish'), ('OTHR', 'Other')], max_length=79, verbose_name='Proteins'),
        ),
    ]
