# Generated by Django 5.2.16 on 2026-08-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_food_protein_hake_trout_kangaroo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='life_stages',
            field=models.CharField(choices=[('UNK', 'Unknown'), ('PUP', 'Puppy'), ('ADL', 'Adult'), ('PTA', 'Puppy To Adult'), ('ALL', 'All-Stages'), ('SNR', 'Senior')], default='UNK', max_length=3, verbose_name='Life Stage'),
        ),
    ]
