# Generated by Django 5.2.16 on 2026-08-07 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_food_life_stage_puppy_to_adult'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='Marks that a superuser has reviewed the entire product description for accuracy. Once reviewed, non-superusers cannot edit the product definition and Product Updater rescans are disabled.', null=True, verbose_name='Reviewed At'),
        ),
        migrations.AddField(
            model_name='product',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_products', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By'),
        ),
        migrations.AlterField(
            model_name='kibble',
            name='kibble_size',
            field=models.CharField(blank=True, choices=[('SM', 'Small'), ('MD', 'Medium'), ('LG', 'Large')], max_length=2, verbose_name='Breed/Kibble Size'),
        ),
        migrations.AlterField(
            model_name='product',
            name='disallowed',
            field=models.BooleanField(default=False, help_text='If set, Storehomes will not be able to intake this Product.', verbose_name='Disallowed'),
        ),
        migrations.AlterField(
            model_name='storageitemintake',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_rows', to='core.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='storageitemouttake',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_rows', to='core.product', verbose_name='Product'),
        ),
    ]
