# Generated by Django 5.2.16 on 2026-08-07 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_product_reviewed_by_reviewed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kibble',
            name='kibble_size',
            field=models.CharField(blank=True, choices=[('SM', 'Small'), ('MD', 'Standard/Unspecified'), ('LG', 'Large')], max_length=2, verbose_name='Breed/Kibble Size'),
        ),
    ]
