# Generated by Django 5.2.16 on 2026-08-07 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_kibble_size_standard_unspecified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treats',
            name='treat_size',
            field=models.CharField(blank=True, choices=[('SM', 'Small'), ('MD', 'Standard/Unspecified'), ('LG', 'Large')], max_length=2, verbose_name='Treat Size'),
        ),
    ]
